### PR TITLE
Fix borrowing problems. Use unwrap_or instead of match

### PR DESCRIPTION
**Pull request by roma0615**
These are the changes I made to get the code to compile on my computer. I also thought it would make more sense to use `unwrap_or` instead of a match statement.

### CODE REVIEW

**Comment by matthias-t** [comment]
Using `unwrap_or` is a good idea, however I don't understand why the other changes are necessary. Could you provide some information about your environment (rust toolchain) and the compiler errors that this fixes?

**Comment by roma0615** [comment]
Running `rustup show` gave me this result:
```
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.25.0 (84203cac6 2018-03-25)
```
So I'm using the `stable-x86_64-apple-darwin` toolchain. Should I try running `rustup update`?

**Comment by matthias-t** [comment]
Yes, try that. The latest `stable` is
```
rustc 1.27.2 (58cc626de 2018-07-18)
```

**Comment by matthias-t** [comment]
We don't care about supporting older releases because this is not a library. Until recently most stuff in the rust ecosystem only built on the latest nightly anyway. We're lucky that rust-clippy is finally coming to stable.

**Pull request merged**
